// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SBOMViewer.Data;

#nullable disable

namespace SBOMViewer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330123623_AddVulnerabilities")]
    partial class AddVulnerabilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SBOMViewer.Data.Dependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ecosystem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("SBOMViewer.Data.DependencyVulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DependencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VulnerabilityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VulnerabilityId");

                    b.HasIndex("DependencyId", "VulnerabilityId")
                        .IsUnique();

                    b.ToTable("DependencyVulnerabilities");
                });

            modelBuilder.Entity("SBOMViewer.Data.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Software");
                });

            modelBuilder.Entity("SBOMViewer.Data.SoftwareDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DependencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DependencyId");

                    b.HasIndex("SoftwareId", "DependencyId")
                        .IsUnique();

                    b.ToTable("SoftwareDependencies");
                });

            modelBuilder.Entity("SBOMViewer.Data.Vulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CveId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CvssScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("CvssVector")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFetchedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CveId")
                        .IsUnique();

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("SBOMViewer.Data.DependencyVulnerability", b =>
                {
                    b.HasOne("SBOMViewer.Data.Dependency", "Dependency")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SBOMViewer.Data.Vulnerability", "Vulnerability")
                        .WithMany("AffectedDependencies")
                        .HasForeignKey("VulnerabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependency");

                    b.Navigation("Vulnerability");
                });

            modelBuilder.Entity("SBOMViewer.Data.SoftwareDependency", b =>
                {
                    b.HasOne("SBOMViewer.Data.Dependency", "Dependency")
                        .WithMany("SoftwareUsages")
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SBOMViewer.Data.Software", "Software")
                        .WithMany("Dependencies")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependency");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SBOMViewer.Data.Dependency", b =>
                {
                    b.Navigation("SoftwareUsages");

                    b.Navigation("Vulnerabilities");
                });

            modelBuilder.Entity("SBOMViewer.Data.Software", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("SBOMViewer.Data.Vulnerability", b =>
                {
                    b.Navigation("AffectedDependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
